# Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You
# may not use this file except in compliance with the License. A copy of
# the License is located at
#
# http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.
#

version: 0.2

phases:
  pre_build:
    commands:
      - set
      - ls -lRt
  build:
    commands:
      - python -m compileall -q src/
      - aws cloudformation package  --template-file cloudformation/cfn-resource-provider.yaml --s3-bucket $DEPLOY_BUCKET --kms-key-id $DEPLOY_KEY --s3-prefix binxio-cfn-certificate-provider --output-template-file packaged-template.json
  post_build:
    commands:
      - aws cloudformation deploy --template-file packaged-template.json --stack-name ${stack_name}"
artifacts:
  files:
    - packaged-template.json
  discard-paths: yes
