---
AWSTemplateFormatVersion: '2010-09-09'
Description: Custom CFN Certificate Provider with DNS validation support
Resources:
  LambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CFNCertificateDomainResourceRecordProvider
      Roles:
        - !Ref 'LambdaRole'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - acm:RequestCertificate
            Resource: '*'
          - Effect: Allow
            Action:
              - acm:DescribeCertificate
              - acm:UpdateCertificateOptions
              - acm:DeleteCertificate
            Resource: !Sub arn:aws:acm:*:${AWS::AccountId}:certificate/*
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-certificate-provider'

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/binxio-cfn-certificate-provider:*
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents

  CFNCustomProviderLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${CFNCustomProvider}
      RetentionInDays: 7

  CFNCustomProvider:
    Type: AWS::Lambda::Function
    Properties:
      Description: CFN Certificate Domain Resource Record Provider
      PackageType: Image
      Code:
        ImageUri: 463637877380.dkr.ecr.eu-central-1.amazonaws.com/xebia/cfn-certificate-provider:1.0.4-f39b907-dirty
      FunctionName: binxio-cfn-certificate-provider
      MemorySize: 128
      Role: !GetAtt 'LambdaRole.Arn'
      Timeout: 300
