AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Name:
    Type: String

Resources:
  Project:
    Type: AWS::CodeBuild::Project
    DependsOn:
      - LogGroup
    Properties:
      Name: !Ref Name
      Description: !Sub '${Name} builder'
      ServiceRole: !Ref 'ProjectRole'
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        PrivilegedMode: true
      Source:
        Type: GITHUB
        Location: !Sub 'https://github.com/binxio/${Name}.git'
        BuildSpec: .buildspec.yaml
        GitCloneDepth: 0
        Auth:
          Type: OAUTH
      Triggers:
        FilterGroups:
         -  - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: "refs/tags/.*"
        Webhook: true

  ProjectRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: codebuild.amazonaws.com
            Condition: {}
      Path: /
      Policies:
        - PolicyName: LambdaBuilder
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeRegions
                  - ecr:GetAuthorizationToken
                Resource: 
                  - '*'

              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                  - ecr:PutImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                Resource: 
                  - !Sub 'arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/xebia/${Name}'

              - Sid: CloudWatchLogsPolicy
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - '*'

  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub xebia/${Name}
      ImageTagMutability: IMMUTABLE
      RepositoryPolicyText:
        Version: '2012-10-17'
        Statement:
          - Sid: read only access
            Effect: Allow
            Principal:
              AWS:
                - '*'
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability

          - Sid: write to owner account
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/codebuild/${Name}'
      RetentionInDays: 7

